name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget cmake ninja-build

      - name: Install LLVM 23
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 23
          sudo apt-get install -y \
            clang-23 \
            clang-tidy-23 \
            lld-23 \
            libc++-23-dev \
            libc++abi-23-dev

      - name: Configure
        run: cmake --preset debug-tests

      - name: Build
        run: cmake --build --preset debug-tests

      - name: Run tests
        run: ctest --test-dir build/debug-tests --output-on-failure